export const TEXT_LIBRARY = {
  APP: {
    NAME: 'R E L Y A C T I V E',
    BRAND_TITLE: 'R E L Y',
    BRAND_SUBTITLE: 'A C T I V E',
    TAGLINE: 'A one stop solution for all community needs',
    WELCOME_TITLE: 'Welcome to Rely Active',
    WELCOME_SUBTITLE: "Let's get your account set up with the essential information",
  },
  BUTTONS: {
    SUBMIT: 'Submit',
    SAVE: 'Save Details',
    CREATE_COMPANY: 'Create Company',
    EDIT_COMPANY: 'Edit Company',
    CANCEL: 'Cancel',
    CONFIRM: 'Confirm',
    ADD_FIELD: 'Add Custom Field',
    SIGN_IN: 'Sign In',
    SIGNING_IN: 'Signing In...',
    SAVING: 'Saving...',
  },
  COMPANY: {
    TITLE: 'Company Details',
    SUBTITLE: 'View and manage organization profile & configuration',
    CREATE_TITLE: 'Create Your Company',
    CREATE_SUBTITLE: "Let's start by setting up your company information",
    EDIT_TITLE: 'Edit Company Information',
    BASIC_DETAILS: 'Basic Details',
    BANK_DETAILS: 'Bank Details',
    FILES_ACCOUNTANT: 'Files & Accountant Details',
    CUSTOM_FIELDS: 'Custom Fields',
    COMPANY_NAME: 'Company Name',
    GST_NUMBER: 'GST Number',
    EMAIL: 'Email Address',
    CONTACT_NUMBER: 'Primary Contact Number',
    ALT_CONTACT_NUMBER: 'Alternate Contact Number',
    HEAD_OFFICE_ADDRESS: 'Head Office Address',
    BANK_NAME: 'Bank Name',
    BRANCH_NAME: 'Branch Name',
    ACCOUNT_NO: 'Account Number',
    IFSC_CODE: 'IFSC Code',
    ACCOUNTANT_NAME: 'Accountant Name',
    ACCOUNTANT_SIGNATURE: 'Accountant Signature',
    DOCUMENT_FILE: 'Company Document / Logo File',
    DOCUMENT_DESC: 'Document Description',
  },
  VALIDATIONS: {
    COMPANY_NAME_REQUIRED: 'Company Name is required',
    EMAIL_REQUIRED: 'Email Address is required',
    INVALID_EMAIL: 'Please enter a valid Email Address (e.g. name@example.com)',
    CONTACT_REQUIRED: 'Contact Number is required',
    INVALID_CONTACT: 'Contact number must start with a digit between 6-9 and be exactly 10 digits',
    INVALID_ALT_CONTACT: 'Alternate contact number must start with a digit between 6-9 and be exactly 10 digits',
    ADDRESS_REQUIRED: 'Head Office Address is required',
  },
} as const

export type TextLibrary = typeof TEXT_LIBRARY
